### ISSUE TITLE
Newtonsoft.Json dependency

### ISSUE THREAD

**Issue by oschwald** [justeat/JustFakeIt#15]
Is there any plans to upgrade the Json.NET dependency? I was unable to use this in my project due to dependency conflicts:

```
Unable to resolve dependencies. 'Newtonsoft.Json 7.0.1' is not compatible with 'JustFakeIt 1.0.0.20 constraint: Newtonsoft.Json (≥ 6.0.0 && < 7.0.0)', 'MaxMind.Db 1.1.0 constraint: Newtonsoft.Json (≥ 7.0.1)'.
```

**Comment by AnthonySteele** [comment]
This should be fixed now.
It's built with `Newtonsoft.Json` 7.0.1
Package spec asks for `Newtonsoft.Json` ≥ 6.0.1 as varius versions of `Newtonsoft.Json` should all work.

**Comment by oschwald** [comment]
Thanks! :+1:
