### ISSUE TITLE
Verifying request headers

### ISSUE THREAD

**Issue by AndrewNewcomb** [justeat/JustFakeIt#31]
As part of a test I wanted to verify that the request contained the http headers I expected the calling code to set up. The HttpResponseExpectation has a Headers property, but the HttpRequestExpectation does not.

I've therefore added a Headers property to HttpRequestExpectation. If expected request headers are specified the ProxyMiddleware checks that they are provided by the caller. If not a BadRequest is returned, along with a body that details what was wrong.

Would you like a pull request?

**Comment by petemounce** [comment]
Sure :)

**Comment by slang25** [comment]
Thanks for the PR @AndrewNewcomb 👍, closing now that #32 is merged
