### ISSUE TITLE
Intermittent errors when running tests in CI

### ISSUE THREAD

**Issue by massimocode** [justeat/JustFakeIt#37]
Hi there

We get intermittent errors when running tests in CI using this library. The stack trace looks like this:
```
Test(s) failed. System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.Net.HttpListenerException : The process cannot access the file because it is being used by another process
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options, Action`1 startup)
   at Microsoft.Owin.Hosting.WebApp.Start(String url, Action`1 startup)
   at JustFakeIt.FakeServer.Start() in c:\projects\justfakeit\JustFakeIt\FakeServer.cs:line 49
   at SOME_ASYNC_METHOD() in C:\BuildAgent\work\5d4c0dd4e428c81b\src\PROJECT\Controllers\FOLDER\TEST_FILE.cs:line 374
   at NUnit.Framework.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Core.NUnitAsyncTestMethod.RunTestMethod()
--HttpListenerException
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
```

Some potentially private stuff has been obfuscated in the stack trace (name of test and file)

If you want links to the builds on teamcity then let me know

**Comment by DrValani** [comment]
Started seeing an increase number of similar failures in our tests projects.

**Comment by jplebre** [comment]
While working on this I've found a similar issue, that seems to be caused by parallel tests being run.

**Comment by slang25** [comment]
I think #34 addresses this. I think it's due to concurrent access of the `Random` object here: https://github.com/justeat/JustFakeIt/blob/ef845ced3fe8933f3704606608168a2cd61b7ba4/JustFakeIt/Ports.cs#L11
Making that `ThreadStatic` should solve it I think.

**Comment by slang25** [comment]
This is probably the most appropraite approach IMO: http://stackoverflow.com/a/19271062/2225808

**Comment by jplebre** [comment]
unless someone has an issue with using ThreadLocal<> it does seem like a clean solution.
I never used it extensively so may be misunderstanding what it does or its side effects.

**Comment by jplebre** [comment]
Right we tracked some of the issues down to the usage of "StopWatch"
Believe it or not it's not accurate. Tons of info on stackoverflow.

Had to change some of the tests to compare UTC values, as that will mean they are compatible per machine
