### ISSUE TITLE
Cannot add response header "Content-Type"

### ISSUE THREAD

**Issue by guatebus** [justeat/JustFakeIt#45]
When adding this header (via `.WithHeader()`) the application throws a `System.ArgumentException` with message "The key 'Content-Type' is already present in the dictionary.". This happens on `server.Start()` invocation.

**Comment by guatebus** [comment]
Same exception occurs when setting this header via the `public HttpExpectation ReturnsFromFile(string relativePath, WebHeaderCollection expectedHeaders = null);` method of the `HttpExpectation` class

**Comment by guatebus** [comment]
The bug is here: https://github.com/justeat/JustFakeIt/blob/b6e602de8215788962830a4afe407f1e48ce45c7/JustFakeIt/ProxyMiddleware.cs#L124

why force the "Content-Type" header to "application/json" when other headers exist? :thinking:

**Comment by slang25** [comment]
Good spot, it seems reasonable to default the `Content-Type` when it is not yet set, but not try to add it when it already exists.
We would welcome a PR. If don't want to, don't worry, I'll put together a fix next weekend.

**Comment by timrose** [comment]
Has this problem been fixed, yet?  I am receiving an error still with the latest stable build v1.0.0.95.
