### ISSUE TITLE
The headers in CapturedRequests are empty even if headers were passed with the request.

### ISSUE THREAD

**Issue by JoshuaDooms** [justeat/JustFakeIt#49]
In the following syntax:
var fakeProxyServer = new FakeServer();
fakeProxyServer.Expect
   .Put(endpointUrl, jsonRequest, new WebHeaderCollection(){{"x-je-feature", testHeaderValue}})
   .Returns(HttpStatusCode.OK);
fakeProxyServer.TryStart();
// Assuming requests were made here
var actualRequests = fakeProxyServer.CapturedRequests;
Assert.That(actualRequests.Any(r=>r.Headers["x-je-feature"] == testHeaderValue));

The Expect syntax works to confirm the headers, but the headers in CapturedRequests do not show the actual request headers.  We also confirmed that the request headers were properly passed using other means.

**Comment by jaimalchohan** [comment]
Please link to a repo in which you have the test case in a minimal solution. Thanks.

**Comment by JoshuaDooms** [comment]
I think this might fix it.  https://github.com/justeat/JustFakeIt/pull/50
